### ISSUE TITLE
[memories] Error: Error querying places: An exception occurred while executing a query: SQLSTATE[25000]

### ISSUE THREAD

**Issue by roru69** [pulsejet/memories#1102] opened 2024-03-29 10:40 UTC
**Describe the bug**
Log showing following error multiple times: 

[memories] Fout: Error querying places: An exception occurred while executing a query: SQLSTATE[25000]: Invalid transaction state: 1207 Update locks cannot be acquired during a READ UNCOMMITTED transaction
	PUT /remote.php/dav/files/[username]/%23Priv%C3%A9%20Foto's%20en%20Video's%20op%20NAS01/pictures/Telefoons/[username]/2024/03/20240328_191556.jpg
	from 192.168.178.9 by [username] at 28 mrt 2024 22:22:10

**To Reproduce**

**Screenshots**

**Platform:**

- OS: Server: Debian 12, Client: Windows 10
- Browser: Microsoft Edge
- Memories Version: 7.02
- Nextcloud Version: 28.0.4
- PHP Version: PHP 8.2.17

**Additional context**
No errors in frontend application. This error is only flooding my logs.

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment] 2024-03-29 17:07
Duplicate of https://github.com/pulsejet/memories/issues/1099

**Closed by pulsejet** 2024-03-29 17:07 UTC
Labels: needs triage
