### ISSUE TITLE
"View in folder" option extremely slow or freezes

### ISSUE THREAD

**Issue by invario** [pulsejet/memories#398] opened 2023-02-09 18:03 UTC
Not sure what's going on here, but when I open a photo or video and I select the "..." menu and go to "View in folder", it opens a new browser tab which loads very, very, very slowly. Eventually it does load up but sometimes it just never finishes and I have to kill the browser app.

I've tried on Windows Firefox and Chrome as well as Android with the same results.

When I have task manager open, I see a new thread launched and network activity on it as well as increasing memory usage.

Nextcloud 25.0.3 and latest version of Memories installed.

I think it depends on where the photo is located. On larger folders, is it attempting to pre-buffer all the thumbnails or something like that? Meaning if I just waited long enough it would load?

Any ideas? 

Thanks again for your wonderful app!

**Comment by pulsejet** [comment] 2023-02-09 18:05
Correct, it's trying to load the entire folder. This is a bug in the Nextcloud Files app rather than memories (you could report it to nextcloud/server).

Duplicate of #237

**Closed by pulsejet** 2023-02-09 18:05 UTC

**Comment by invario** [comment] 2023-02-09 18:07
> Correct, it's trying to load the entire folder. This is a bug in the Nextcloud Files app rather than memories (you could report it to nextcloud/server).
> 
> Duplicate of #237

Ahhh thanks so much.
