### ISSUE TITLE
Search or filter function

### ISSUE THREAD

**Issue by flammableliquids** [pulsejet/memories#742] opened 2023-07-16 02:17 UTC
One thing I find myself looking for is the ability to find photos that match a specific criterion.

I would love to be able to go to a page and filter to find the images I need.

For examples:
- photos tagged with both dogs and beach.
- two specifically named people, in the same photos.

Having the existing time based layout would eliminate the need to filter by time IMHO.

**Comment by pulsejet** [comment] 2023-07-24 00:21
Duplicate of #674

**Closed by pulsejet** 2023-07-24 00:21 UTC
Labels: feature
