### ISSUE TITLE
Memories Android App can not download files.

### ISSUE THREAD

**Issue by VirginioMiranda** [pulsejet/memories#1221] opened 2024-06-08 20:49 UTC
**Describe the bug**
The memories app from android  does not download any files. It doesn't matter if it's an album or a folder or even an isolated file. 
 
**To Reproduce**
Download Memories from google play and  install. 

**Platform:**

- OS: Kubuntu 24.04
- Browser: Firefox Snap 126.0.1
- Memories Version: 1.12 
- Nextcloud Version: Snap 28.0.6snap1
- PHP Version: 8.2.18

**Additional context**
 I believe the problem occurs because the memories application is not able to log in securely. It is only possible to access the application by disabling certificate verification that is self signed (unsafe mode). 

So the message when trying to log in secure way is:

" Error: java .security.cert.CertPathValidatorException: Trust anchor for certification path not found.

The problem does not occur on Photos app, Nextcloud app, NC Password app and Notes app; All of them are able to log in checking the self sign certificate.

**Comment by yurividal** [comment] 2024-06-19 05:55
This is a duplicate of [1155](https://github.com/pulsejet/memories/issues/1155)

**Closed** 2024-06-23 23:56 UTC
Labels: duplicate
