### ISSUE TITLE
Select all photos [feature request]

### ISSUE THREAD

**Issue by MarkWieczorek** [pulsejet/memories#527] opened 2023-03-26 21:08 UTC
**Is your feature request related to a problem? Please describe.**
With the latest version of Memories, you can select individual photos by clicking on the check mark in the upper left of the image, or you can select all photos for a specific day by clicking on the check mark next to the day. However, to the best of my knowledge, there is no way to select all photos in a given folder or album. This would be very useful!

**Describe the solution you'd like**
Add some kind of option at the top of the page for "Select all".

**Comment by pulsejet** [comment] 2023-03-26 21:24
Duplicate of #132

**Closed by pulsejet** 2023-03-26 21:24 UTC
Labels: feature

**Comment by MarkWieczorek** [comment] 2023-03-26 21:42
Thanks for reopening that issue!
