### ISSUE TITLE
linuxserver/nextcloud docker container adding intel quick sync results in "VA-API device (/dev/dri/renderD128) not found"

### ISSUE THREAD

**Issue by kpaaro** [pulsejet/memories#586] opened 2023-04-18 22:58 UTC
**Describe the bug**
Adding intel quick sync results in "VA-API device (/dev/dri/renderD128) not found.

**To Reproduce**
I am running this on an Unraid server. I have passed in the iGPU to plex where it works.
I used this to add my intel iGPU to the container:
``` devices:
      - /dev/dri:/dev/dri
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libva|libva-intel-driver|intel-media-driver|mesa-va-gallium
```
which results in a docker run: 
```
docker run
  -d
  --name='nextcloud'
  --net='bridge'
  -e TZ="Europe/Kiev"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="NAS"
  -e HOST_CONTAINERNAME="nextcloud"
  -e 'DOCKER_MODS'='linuxserver/mods:universal-package-install'
  -e 'INSTALL_PACKAGES'='libva|libva-intel-driver|intel-media-driver|mesa-va-gallium|mesa-va-drivers'
  -e 'PUID'='1002'
  -e 'PGID'='100'
  -e 'UMASK'='002'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='https://[IP]:[PORT:443]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nextcloud-logo.png'
  -p '7443:443/tcp'
  -v '/mnt/user/nextcloud/':'/data':'rw'
  -v '/mnt/user/memories/':'/mnt/memories':'rw'
  -v '/mnt/cache/appdata/nextcloud':'/config':'rw'
  --device='/dev/dri' 'lscr.io/linuxserver/nextcloud'
232cf73116974c8cb4c811aa2d07ee1d196ca276f32f6e81b1eff0646962d003
```

**Platform (please complete the following information):**
UNRAID
linuxserver/nextcloud

Any suggestions on how to resolve this issue?

**Comment by pulsejet** [comment] 2023-04-19 02:24
Duplicate of #577

**Closed by pulsejet** 2023-04-19 02:24 UTC
Labels: needs triage
