### ISSUE TITLE
Range selection is needed

### ISSUE THREAD

**Issue by darguez** [pulsejet/memories#179] opened 2022-11-10 00:00 UTC
When you want to add hundreds of photos to an album, it would be nice to select a range (SHIFT+Click) instead clicking one by one.

**Comment by pulsejet** [comment] 2022-11-10 02:06
Duplicate of #28

**Closed by pulsejet** 2022-11-10 02:06 UTC

**Comment by pulsejet** [comment] 2022-11-17 14:55
For future ref, this is implemented in v4.7
