### ISSUE TITLE
Info button don't do anything

### ISSUE THREAD

**Issue by Mike710Shine** [pulsejet/memories#950] opened 2023-12-01 08:23 UTC
**Describe the bug**
If i make an picture big and hit the Info button it does nothing.

**To Reproduce**
Make the picture big an hit the button

**Screenshots**
![grafik](https://github.com/pulsejet/memories/assets/19763591/07ff3448-a91e-436c-b1b5-7393ab1beab7)

**Platform:**

- OS: Windows 
- Browser: Firefox, Chrome
- Memories Version: 6.1.5
- Nextcloud Version: 27.1.4 Docker
- PHP Version: 8.2.13

**Additional context**

- Any errors in the JS console? No
- Any errors in the Nextcloud server logs? No

In the Android App the Info works fine.

**Comment by pulsejet** [comment] 2023-12-01 15:09
Logs?

**Comment by Mike710Shine** [comment] 2023-12-01 19:08
Ok i don't know what i do but now it works very strange. But anyway i close this Ticket.

**Comment by Mike710Shine** [comment] 2023-12-01 21:27
No not that i know. Sorry but i understand without any logs and so you can do nothing no Problem with the workaround that i go to Files it works and this is ok for me thanks for your time.

**Comment by RichardPillay** [comment] 2024-03-02 23:58
> > And no logs sorry.
> 
> Can't do anything then. I assume there's nothing in JS console either?

I can confirm that this is definitely an issue. Are you able to reproduce it locally? If you can, then possibly something may appear in your log as opposed to ours. I know that logs on a user's system is set to Info, but on your system, set to Debug, something may show up that we won't see. And the discovery by @Mike710Shine that it only works if you go from Memories to Files and back to Memories suggests that something is being set up in the UI in Files that Memories depends on, but is not initializing itself. Possibly something that is always available on your development system.

Is there any help available on setting up a development system? Besides this issue, I have other issues with Memories. Problem is, I can't log an issue because I have not figured out yet if the problem is with memories, or my own server. I get a core-dump in Apache2, which strongly suggests the problem is on my side. But setting up a development system will help me get to grips with both issues.

**Comment by Mike710Shine** [comment] 2024-03-03 08:58
These here the two Logdata from my dev env after login and direct go to Memories and the Info button not work.

{"reqId":"BvFlSzVsCZblwaYWiaYq","level":0,"time":"2024-03-03T08:56:39+00:00","remoteAddr":"192.168.178.21","user":"ad_mike710shine","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/files?itemId=9901&format=json","message":"retrieving related to item files.9901","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0","version":"28.0.2.5","data":{"app":"related_resources"}}
{"reqId":"BvFlSzVsCZblwaYWiaYq","level":0,"time":"2024-03-03T08:56:39+00:00","remoteAddr":"192.168.178.21","user":"ad_mike710shine","app":"related_resources","method":"GET","url":"/ocs/v2.php/apps/related_resources/related/files?itemId=9901&format=json","message":"get related to files.9901 - null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0","version":"28.0.2.5","data":{"app":"related_resources"}}

Maybe this will help

**Comment by sokai** [comment] 2024-03-28 12:18
I experience the same issue (with current NC + Memories versions).

If I click on the `(i)` button, the browser/JS console shows this error.

```js
TypeError: s is null
    destroy mainFilesSidebarLoader.js:84
    beforeDestroy SidebarTab.vue:127
    VueJS 35
    close Sidebar.vue:505
    close memories-main.js:2
    hideSidebar memories-main.js:2
    closeSidebar memories-main.js:2
    toggleSidebar memories-main.js:2
    click memories-main.js:2
    click memories-main.js:2
    un memories-main.js:2
    n memories-main.js:2
    un memories-main.js:2
    $emit memories-main.js:2
    click memories-main.js:2
    un memories-main.js:2
    n memories-main.js:2
    _wrapper memories-main.js:2
vue.runtime.esm.js:3065:16
```

Maybe this helps. (For me it says _nothing_  … #sry)
#ty + KR

**Comment by pulsejet** [comment] 2024-03-28 14:42
So I'm not sure its the same thing but there's a known bug in v5-v7 which could cause this. Look out for the next release.

**Comment by lckarssen** [comment] 2024-03-30 22:32
Just to confirm this on Linux, with both Firefox and Chromium. As mentioned above, going directly from Dashboard to Memories means the info button doesn't show anything, whereas going to Files and the to Memories makes the info button work. This is on Nextcloud 28.0.3 with Memories v6.1.1, but this bug was there before v6 as well.

**Comment by pulsejet** [comment] 2024-03-31 00:07
Please update to v7.1 when it comes out. This is a confirmed bug that's still present in the latest release but (hopefully) fixed on master

**Comment by pulsejet** [comment] 2024-04-01 21:14
Please upgrade to v7.1.0 and provide feedback if the issue persists.

**Comment by Mike710Shine** [comment] 2024-04-03 07:33
The v7.1.0 solve the Problem thanks so much.

**Closed** 2024-04-03 09:20 UTC
Labels: bug, needs details
