### ISSUE TITLE
Seeing faces of other users

### ISSUE THREAD

**Issue by mic05** [pulsejet/memories#502] opened 2023-03-19 19:44 UTC
**Describe the bug**
A user has shared his folder which contains the images with another user. In memories, now there are the faces of the other user visable and can't be  merged because there is an error message: Only user "XXX" can update this person

**To Reproduce**
Steps to reproduce the behavior: Share image folder, let recognize run and get the face clusters, go to memories and see the clusters of another user

**Screenshots**
Can't share this sensitive data.

**Platform (please complete the following information):**

- OS: [e.g. iOS]: Debian 11
- Browser [e.g. chrome, safari]: Chrome
- Version [e.g. 4.1.0]: Recognize: 3.6.3, Memories: 4.12.2

**Additional context**
None

**Important: Are all of the following are true?**

- I have followed the [configuration steps](https://github.com/pulsejet/memories/wiki/Configuration).: Yes
- I am NOT using `OCCWeb` to run `occ` commands: Yes
- The problem persists after clearing browser cache: Yes

**Comment by pulsejet** [comment] 2023-03-20 20:27
Duplicate of #500

**Closed by pulsejet** 2023-03-20 20:27 UTC
Labels: needs triage
