### ISSUE TITLE
Android App: memories (eg. 3 years ago) doesn't play or black screen

### ISSUE THREAD

**Issue by thegabriele97** [pulsejet/memories#1175] opened 2024-05-03 13:02 UTC
**Describe the bug**
If I click on a memory (like 3 years ago) nothing works, this means that I see that a transcode in ongoing server side looking at the process but I continue to see the same static preview. If I do a swipe (i.e. the memory has > 1 element in it) I see a black screen.

**Platform:**
- OS: Android
- Memories Version: latest
- Nextcloud Version: 27.1
- PHP Version: 8.1 fpm

- Any errors in the Nextcloud server logs? Nothing

**Comment by pulsejet** [comment] 2024-05-03 15:55
Duplicate of #1149

**Closed by pulsejet** 2024-05-03 15:55 UTC
Labels: needs triage
