### ISSUE TITLE
Invalid type for system config preview_max_x, expected integer, got string [Nextcloudpi]

### ISSUE THREAD

**Issue by vovchykbratyk** [pulsejet/memories#1176] opened 2024-05-03 18:40 UTC
**Describe the bug**
After installing the Memories app, the administration panel link yields the following error toast:

`invalid type for system config preview_max_x, expected integer, got string`

**To Reproduce**
1. Fresh install of nextcloudpi
2. Fresh install of memories app

**Screenshots**

<img width="718" alt="Screenshot 2024-05-03 at 14 30 38" src="https://github.com/pulsejet/memories/assets/40668075/e8a493bf-9d0a-403d-ae61-4d8fe4221b13">

**Platform:**

- OS: [e.g. iOS] MacOS (on the Pi: **Linux 6.6.28-current-bcm2712 aarch64**)
- Browser: [e.g. Chrome, Safari] Brave, Safari, Edge
- Memories Version: [e.g. 4.1.0] **7.3.0**
- Nextcloud Version: [e.g. 25.0.6] **28.0.4**
- PHP Version: [e.g. 8.1] **8.1.28**

**Additional context**
RPI5, 8GB version

- Any errors in the JS console?
- Any errors in the Nextcloud server logs? - Not that I could tell that had to do with Memories or the error reported above.

**Comment by pulsejet** [comment] 2024-05-03 18:46
Duplicate of #1168

**Closed by pulsejet** 2024-05-03 18:46 UTC
Labels: needs triage

**Comment by pulsejet** [comment] 2024-05-03 19:33
Please try 7.3.1
