### ISSUE TITLE
Don't show images w/o coordinates on the map

### ISSUE THREAD

**Issue by jonas-w** [pulsejet/memories#446] opened 2023-02-27 10:22 UTC
As described in the title, if images don't have coordinates, they get displayed at 0.0, 0.0 which is right next to Africa. Would be cool if they just wouldn't get displayed at all.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/32615971/221537697-a8301aa4-f1c7-4d97-a6cc-737d2d6a6749.png">

**Comment by pulsejet** [comment] 2023-02-27 17:26
This is already fixed in v4.11.1, you just need to reindex (otherwise run a simple query to change everything with lat long zero to null in the oc_memories table)

**Comment by pulsejet** [comment] 2023-02-27 17:27
Duplicate of #420

**Closed by pulsejet** 2023-02-27 17:27 UTC

**Comment by jonas-w** [comment] 2023-02-28 08:32
Thanks! Sorry couldn't find it when searching on GitHub :|
