### ISSUE TITLE
[Feature Request] Easily select multiple photos

### ISSUE THREAD

**Issue by jacotec** [pulsejet/memories#167] opened 2022-11-06 16:27 UTC
When you want to add tens or even hundreds of photos into an album it's very tortuous to tick each single photo.

It would be very helpful to be able to select complete rows or even a start picture and then (with shift) an end picture.

**Comment by pulsejet** [comment] 2022-11-07 02:01
Duplicate of #28

**Closed by pulsejet** 2022-11-07 02:01 UTC
