### ISSUE TITLE
Make it possible to upload photos directly from the app 

### ISSUE THREAD

**Issue by Akruidenberg** [pulsejet/memories#69] opened 2022-10-16 10:05 UTC
In the upcoming photo app 25, nextcloud get an option to  upload photos from the photo app.
It would be nice to have such option in memories also.

**Comment by meichthys** [comment] 2023-02-11 04:22
Along with this, It would also be good to have a way to upload directly to an album like we can do in the default Photos app.

**Comment by meichthys** [comment] 2023-02-23 18:52
We may also need to re-index after uploading in order to get the photo to show in the timeline right away(?)

**Comment by pulsejet** [comment] 2023-02-23 19:19
That happens through a hook anyway; for example if you upload through files or Photos, then it'll index it right away. So the only missing thing is the UI.

**Comment by meichthys** [comment] 2023-02-23 19:41
Ok, Nice! Looking forward to it 👍

**Comment by major-mayer** [comment] 2023-05-23 21:57
Does this feature request also cover the case that a shared album does currently not allow uploading new images, even when the mode is set to "editable" ?

**Comment by johnSamilin** [comment] 2024-01-18 08:26
Hi everyone, is this feature request still actual?

**Comment by johnSamilin** [comment] 2024-01-22 11:33
Feel free to assign this issue to me, I'm planning to start working on it

**Comment by johnSamilin** [comment] 2024-02-15 11:42
Is it ok if I use https://github.com/nextcloud-libraries/nextcloud-upload? This will cause @nextcloud/vue to be upgraded to version 8.6.2 and all the imports of components (@nextcloud/vue/dist/Components/NCButton) will be changed also (to @nextcloud/vue/dist/Components/NCButton.js)

**Comment by Havouza15** [comment] 2024-02-16 11:42
Because the upload directly is missing I use Photosync instead on my phone to autotransfer all photos. I have it set to upload it directly when the photo is taken but there is many different options. I really hope this will come also on the Memories app

**Comment by johnSamilin** [comment] 2024-02-21 11:05
Hey guys, I'm having troubles with my local nextcloud server and could use some help. Could someone try to build this branch https://github.com/johnSamilin/memories/tree/issue-69.uploading-button and upload a photo? I have implemented UI and added integration with backend but seems like I'm stuck with improper server setup.

**Comment by major-mayer** [comment] 2024-02-26 22:13
Maybe @pulsejet could take a look?

**Closed** 2024-03-20 06:09 UTC
Labels: feature, priority: high

**Comment by ChildLearningClub** [comment] 2024-03-20 23:19
Great work @johnSamilin and @pulsejet!

**Comment by gymnae** [comment] 2024-03-21 10:19
That is a great feature. Could that also be enable for publically shared folders and albums on a per share basis?

**Comment by ChildLearningClub** [comment] 2024-03-21 12:21
> That is a great feature. Could that also be enable for publically shared folders and albums on a per share basis?

Just asked this same question earlier today https://github.com/pulsejet/memories/pull/1073

**Comment by Joeviocoe** [comment] 2024-03-22 15:15
I thought this issue was for the mobile app.  Guess not.  I'm glad to see the direct upload feature working on the web app, but that was already pretty simple to tab over to the Files or Photo apps to upload something.
On the Android app, I have to maintain a completely separate phone app to upload.  So I'm patiently waiting for the Android update to include the feature.  Hoping soon maybe since the hard part of creating the function server side is done.

**Comment by pulsejet** [comment] 2024-03-22 16:17
> On the Android app, I have to maintain a completely separate phone app to upload. 

This is by design and will always be the case; more related to the philosophy of not reinventing the wheel. Auto upload is hard enough that Nextcloud's implementation isn't particularly fantastic. The whole point of using Nextcloud as a base / framework is to not reinvent things like auto upload.

**Comment by Joeviocoe** [comment] 2024-03-22 17:54
> Auto upload is hard enough that Nextcloud's implementation isn't particularly fantastic. The whole point of using Nextcloud as a base / framework is to not reinvent things like auto upload.

I'm still confused about what this issue was created for.  "Auto upload" refers to watching local folders on your phone and automatically uploading changes (new, modified, deleted files) to Next Cloud, right?  Essentially an automatic SYNC feature.
Not the MANUAL OPTION "upload button" that is now available on the web app?

I agree that the local folder "sync" feature should not be included with Memories.  But the direct "manual upload" is now a part of Memories at least for desktop browsers.  So it should not be too much to have the Android app (which is a wrapper for the web app IIRC) just render that same button and bring up the iOS or Android native file picker using the API.

**Comment by pulsejet** [comment] 2024-03-22 18:20
Ah yes, I (incorrectly) assumed _you_ misunderstood the issue (haha).

Yes, the android app should also get the manual upload button hopefully soon.

> On the Android app, I have to maintain a completely separate phone app to upload.

This is the part that confused me to think you're confused (lmao). You'd still need a separate app anyway for the sync upload.

**Comment by Joeviocoe** [comment] 2024-03-22 18:23
Ah, okay glad that's cleared up.  I look forward to the next Android app update for Memories.

> You'd still need a separate app anyway for the sync upload.

Not really a feature I need myself, I am fine manually uploading and not syncing.
