### ISSUE TITLE
Add/document alternative to `occ` and `OCCWeb`

### ISSUE THREAD

**Issue by stefan2904** [pulsejet/memories#514] opened 2023-03-23 17:01 UTC
**Is your feature request related to a problem? Please describe.**
To create the index, you need to run a `occ` command. But in some nextcloud deployments, users dont have SSH access to the server, thus they cannot run `occ` directly. For this, `OCCWeb` exists, but in your wiki you state "DO NOT use OCCWeb to run any command". I assume there is a reason for this. ;-) 

**Describe the solution you'd like**
Provide means to create the index and initialize places for people without `occ` access. As an alternative, document that this is not possible, and/or what the expectations are for people who dont have SSH access. 

**Additional context**
(To my understanding, new pictures will be indexed anyways, but there is no way for existing media?)

**Comment by EVOTk** [comment] 2023-03-23 22:13
Hello,
Yes OCCWeb is deprecated, the reason is here : https://github.com/Adphi/occweb#%EF%B8%8F-deprecated-%EF%B8%8F

If it gives you an idea, I use a scheduled task (cron) that I trigger manually in Openmediavault when I need to do a re-indexing command

![image](https://user-images.githubusercontent.com/45015615/227376348-ff904376-8a4c-40b8-ba1f-4133d1a4a8be.png)

**Comment by pulsejet** [comment] 2023-03-24 06:20
Duplicate of #110

**Closed by pulsejet** 2023-03-24 06:20 UTC
Labels: feature
