### ISSUE TITLE
Add button in settings dialog to re-index

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#404] opened 2023-02-10 18:18 UTC
Currently we need to drop to the command line to re-index. It would be nice if there was a button in the settings dialog to re-index.

I'm not sure if this would be possible for normal users - it may require admin rights(?)

**Comment by pulsejet** [comment] 2023-02-10 20:25
Duplicate of #110

**Closed by pulsejet** 2023-02-10 20:25 UTC

**Comment by meichthys** [comment] 2023-02-10 20:28
I thought i remember there being an issue for this, I just couldn't find it!
