### ISSUE TITLE
Show single shared files in the timeline

### ISSUE THREAD

**Issue by thegrasshopper104** [pulsejet/memories#1007] opened 2024-01-18 22:33 UTC
If you share a file with other users, it won't show up in their Memories timeline. They show up in their root folder and their Memories settings are also set to /. Photos does show these files.
**To Reproduce**
1. Share files individually with a group or user
2. Check the timeline from another account: the file is there but missing from Memories

**Comment by pulsejet** [comment] 2024-01-19 17:43
Duplicate of #457

**Closed by pulsejet** 2024-01-19 17:43 UTC
Labels: needs triage
