### ISSUE TITLE
Live photos don't play

### ISSUE THREAD

**Issue by thegrasshopper104** [pulsejet/memories#1014] opened 2024-01-23 10:58 UTC
**Describe the bug**
Live photos from iPhones or Motion photos from android phones don't play. The live photo icon shows Tried in the web interface and the android app (1.6 from Google Play)

To Reproduce, upload some live photos.

**Platform:**
- OS: Android 14, kernel 5.10.177-android13-4-00003-ga7208022a7ea-ab10815828
- Browser: Vivaldi desktop, Android
- Memories Version: 6.2.2
- Nextcloud Version: 27.1.4 (snap)

- Any errors in the JS console? _...&liveid=self__trailer&transcode=dvl7t0po6mu0 says: `{"message":"Could not create temporary file (0)"}`_

- Any errors in the Nextcloud server logs? nothing relevant

**Comment by thegrasshopper104** [comment] 2024-02-10 22:15
Here's a weird thing: Pixel photos edited using Google Photos (locally) before the upload do play, but the original file doesn't

**Comment by pvince** [comment] 2024-02-26 14:57
Also, much, much older motion photos DO play. Scrolling back through my history of uploaded photos, I can see a motion picture from Dec. 4, 2023 plays fine, however one taken on Dec. 14, 2023 does not.

From the scattershot I tested, all before Dec 4th play fine, all after Dec 14th do not.

**Comment by AstroPhotoJay** [comment] 2024-03-08 02:25
I'm experiencing the same issue.

Date of last of motion photo displaying correctly in NC Memories: 03 Dec 2023

Since then, I get the following error in my log whenever a motion photo is uploaded
`{"reqId":"GTozW35FA5qHjODfGRfo","level":3,"time":"2024-03-07T23:48:48+00:00","remoteAddr":"172.17.0.1","user":"REDACTED","app":"PHP","method":"PUT","url":"/remote.php/dav/files/REDACTED/My%20Photos/Phone%20Backup/2024/03/PXL_20240307_234521963.MP.jpg","message":"Undefined array key \"Copy2:DirectoryItemLength\" at /var/www/html/custom_apps/memories/lib/Db/LivePhoto.php#78","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.28.0","version":"28.0.3.2","data":{"app":"PHP"},"id":"65ea71c3f129b"}`

**MOBILE DEVICE**
- Make/Model: pixel 7 pro
- OS: Stock android (whatever the latest version is
- App: Nextcloud Android App 3.28.0

**PLATFORM INFO**
- OS: Ubuntu desktop 22.04
- Memories Version: 6.2.2
- Nextcloud Version: 28.0.3 (Apache Docker)
- PHP Version: 8.2.16

**PHP**
- Version: 8.2.16
- Memory limit: 5.9 GB
- Max execution time: 3600
- Upload max size: 5.9 GB
- OPcache Revalidate Frequency: 60
- Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, bz2, posix, random, Reflection, standard, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, Phar, exif, ftp, gd, gmp, imagick, imap, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, smbclient, sodium, sysvsem, zip, libsmbclient, Zend OPcache

**Comment by ZeroKun265** [comment] 2024-03-19 20:42
Well I've got the same issue and editing the photo with Google photo did work
Wanted to try and edit it in memories but ofc it told me it's a disabled feature.

Would love to help if you need something

**Comment by csm10495** [comment] 2024-03-20 04:30
Same issue on a fresh memories install. Motion photos (Android in my case) won't play.

I can tap the play icon but nothing happens.

**Comment by lsde** [comment] 2024-03-24 07:41
I can confirm that live photos made by Pixel 7a currently don't play, but photos shot before December 6 feature drop do play.

In the following album, there is a live photo taken by Pixel 5 (plays), followed by photo taken by Pixel 7a on Dec. 3 just before the feature drop (plays), and another one shot on Jan. 9 after the feature drop (doesn't play). 

Currently I do not have time to investigate it further myself, therefore I hope at least these photos can serve a purpouse to somebody who does.
https://nextcloud.lsde.org/apps/memories/a/Q1FvDB9kCozTegPLi0p4sF8lUilELrA4

**Comment by thegrasshopper104** [comment] 2024-03-24 16:23
Memories 7.0.2, Android v1.7 on Nextcloud AIO v8.0.0 shows Android motion photos :)

but still doesn't play iPhone live photos.
not sure if this is relevant:
```
[24-Mar-2024 09:51:14] ERROR: epoll: unable to remove fd 12
[24-Mar-2024 09:51:14] ERROR: epoll: unable to remove fd 15
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 73728 bytes) in /var/www/html/custom_apps/recognize/lib/Classifiers/Classifier.php on line 360
Warning: Error rebuilding maker notes (may be corrupt) - /mnt/ncdata/aronkvh/files/InstantUpload/Camera/PXL_20240223_125337353.RAW-02.ORIGINAL.dng
Warning: Error rebuilding maker notes (may be corrupt) - /mnt/ncdata/aronkvh/files/InstantUpload/Camera/PXL_20240308_204218401.RAW-02.ORIGINAL.dng
Warning: Error rebuilding maker notes (may be corrupt) - /mnt/ncdata/aronkvh/files/InstantUpload/Camera/PXL_20240228_170439333.RAW-02.ORIGINAL.dng
```
.
.
.
```
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 2608592 bytes) in /var/www/html/lib/private/Files/Storage/Local.php on line 327
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 2608592 bytes) in /var/www/html/lib/private/Files/Storage/Local.php on line 327
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 2608592 bytes) in /var/www/html/lib/private/Files/Storage/Local.php on line 327
[24-Mar-2024 16:19:26] ERROR: epoll: unable to remove fd 12
[24-Mar-2024 16:19:26] ERROR: epoll: unable to remove fd 15
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 2608592 bytes) in /var/www/html/lib/private/Files/Storage/Local.php on line 327
```

**Comment by pulsejet** [comment] 2024-03-24 18:07
> Currently I do not have time to investigate it further myself, therefore I hope at least these photos can serve a purpouse to somebody who does.
> https://nextcloud.lsde.org/apps/memories/a/Q1FvDB9kCozTegPLi0p4sF8lUilELrA4

This helps. Please leave this link up for a few days.

> but still doesn't play iPhone live photos.
not sure if this is relevant:

Do you have transcoding enabled? The error messages are irrelevant; please check the JS console for any other errors and provide samples.

**Comment by pulsejet** [comment] 2024-03-24 18:31
> and another one shot on Jan. 9 after the feature drop (doesn't play)

@lsde what's happening here is this image was indexed with Memories v6 but the bug here was fixed only in v7. This however won't invalidate the previous index. All you need is to reindex this forcibly.
```bash
occ memories:index --force
```

You can specify a folder to the command to reindex more specifically,
```bash
occ memories:index --force --folder /path/to/folder
```

This reminds me there should be an option to reindex selected files for cases like this.

**Comment by thegrasshopper104** [comment] 2024-03-24 19:56
> > Currently I do not have time to investigate it further myself, therefore I hope at least these photos can serve a purpouse to somebody who does.
> > https://nextcloud.lsde.org/apps/memories/a/Q1FvDB9kCozTegPLi0p4sF8lUilELrA4
> 
> This helps. Please leave this link up for a few days.
> 
> > but still doesn't play iPhone live photos.
> > not sure if this is relevant:
> 
> Do you have transcoding enabled? The error messages are irrelevant; please check the JS console for any other errors and provide samples.

Transcoding is enabled, I don't console errors. [Here](https://felho.aronkvh.hu/apps/memories/a/ZszurOdCxLZqjwPSwwOgAAWxeneLY9Ky) the first one doesn't play (iPhone) and the other 2 work (Pixel)

**Comment by pulsejet** [comment] 2024-03-25 05:41
> Not found (live video file)

There's your error; the live photo's video part simply doesn't exist. Are you sure it was uploaded to begin with?

**Comment by thegrasshopper104** [comment] 2024-03-25 08:48
> > Not found (live video file)
> 
> There's your error; the live photo's video part simply doesn't exist. Are you sure it was uploaded to begin with?

Oh, it's an easy explanation then. Apparently Safari doesn't upload the .mov just the .jpeg.
Should I close the issue?

**Comment by pulsejet** [comment] 2024-03-25 19:08
You could try uploading the mov too, if that works then we can close this issue.

**Comment by ZeroKun265** [comment] 2024-03-25 19:15
Wait, I updated memories and now I can see the motion photos on both the android app and the chrome browser on Android.
But on pc, with Arch Linux and Chrome 123.0.6312.58 (chrome, not chromium) they don't show, I don't know if it's related

**Comment by pulsejet** [comment] 2024-03-25 19:18
@ZeroKun265 do you have transcoding set up? It's likely that your mobile supports the format but desktop doesn't.

**Comment by ZeroKun265** [comment] 2024-03-25 19:21
> @ZeroKun265 do you have transcoding set up? It's likely that your mobile supports the format but desktop doesn't.

Yes the "Enable Transcoding" is on and it's using the internal transcoder
I'm trying a full update on arch and I'll also test it out on my Windows partition, if it works on Windows I'll just mark it as a "classic Linux" moment

**Comment by pulsejet** [comment] 2024-03-25 19:29
Either way, do pull the logs and file a _separate _ issue for this

**Comment by lsde** [comment] 2024-03-30 14:14
> > and another one shot on Jan. 9 after the feature drop (doesn't play)
> 
> @lsde what's happening here is this image was indexed with Memories v6 but the bug here was fixed only in v7. This however won't invalidate the previous index. All you need is to reindex this forcibly.
> 
> ```shell
> occ memories:index --force
> ```
> 
> You can specify a folder to the command to reindex more specifically,
> 
> ```shell
> occ memories:index --force --folder /path/to/folder
> ```
> 
> This reminds me there should be an option to reindex selected files for cases like this.
> 
> #1095

ok, you're obviously right, reindexing the folder did fix the issue for me indeed!

**Comment by pulsejet** [comment] 2024-04-02 15:47
Closing this, if the issue persists please open a new issue (since it will likely be unrelated to this one at this point)

**Closed by pulsejet** 2024-04-02 15:47 UTC
