### ISSUE TITLE
Select All in albums/folders

### ISSUE THREAD

**Issue by luckkmaxx** [pulsejet/memories#1088] opened 2024-03-23 13:07 UTC
We cant select all items inside a folder. It could be fine one or two options:
- A "select all" option in the three dots.
- Ability to select all items between first picked and last long-tapped image.

**Comment by pulsejet** [comment] 2024-03-23 17:02
> Ability to select all items between first picked and last long-tapped image.

Just use Shift+Select: https://youtu.be/vUNJxJMauXk

Duplicate of #132

**Closed by pulsejet** 2024-03-23 17:02 UTC
Labels: feature

**Comment by luckkmaxx** [comment] 2024-03-30 14:49
Ok maybe I forget to mention this is in mobile UI
