### ISSUE TITLE
Non-admin (regular) user can't download images

### ISSUE THREAD

**Issue by dm-vodopyanov** [pulsejet/memories#366] opened 2023-01-22 19:13 UTC
**Nextcloud:** 24.0.9
**Memories:** 3.10.1

**To reproduce:** admin user (ADMIN) has folder with photos on external storage (mentioning external storage just in case). Let it be /ADMIN/files/photos. ADMIN shares this folder to user USER, read-only access. USER creates folder "my_folder" and moves shared photos folder to "my_folder". USER opens some photo in /USER/files/my_folder/photos through Memories - it opens fine. But when USER tries to download it (... -> Download), redirect to error page appears with the following message (IP address market with Xs):
```
Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: XX.XXX.XXX.XXX
Request ID: XTRAigon8NV4nRuoCXAS
```

**Investigation:** the photo which USER tries to download in browser is downloadable in browser for ADMIN. E.g., ADMIN downloads photo in browser, everything is ok, then logging out, USER logs in in the same browser, tries to download the same photo - can't download it and receives error message. Meanwhile, the photo is downloadable for USER in Files. So looks like Memories-specific bug.

**Screenshot:**
![repro](https://user-images.githubusercontent.com/5374181/213935281-ed191b2b-5b27-48e7-a803-eb09a081afd3.png)

**Comment by pulsejet** [comment] 2023-01-22 19:59
Duplicate of #365 
Video playback and download image are equivalent functions.

**Closed by pulsejet** 2023-01-22 19:59 UTC
