### ISSUE TITLE
Ability to move selected faces to NEW cluster 

### ISSUE THREAD

**Issue by illnesse** [pulsejet/memories#117] opened 2022-10-26 14:42 UTC
Like #78 but create a new cluster (maybe ask user for name?)

**Comment by pulsejet** [comment] 2022-10-26 17:10
Not sure this is possible without messing with the recognize table ...

**Comment by pulsejet** [comment] 2022-10-26 17:26
The problem will arise if recognize decides to change their internal data structure for some reason. The better solution would be to add explicit support for this there.

**Comment by rhatguy** [comment] 2022-10-27 12:39
I have this exact issue and it creates an interesting problem.  I have faces from person1 and person2 in the same currently unnamed cluster.  I can't create the person1 name without moving person2 into person1s name right now.  I suppose the only way around this right now is to go ahead and name the cluster for person1, then go back into the person1 cluster and remove person2 from the cluster.  Seems like the ability to create a NEW name from selected people from an existing cluster will be a big deal in the long term.

**Comment by phil-lipp** [comment] 2023-01-19 08:49
As the recognize app is becoming more mature and face classification is progressing through my photo library, I feel the need to bump this issue. I have a lot of cases where 2 or 3 similar looking people are in one single cluster and none of them have their own cluster yet. On one hand this means that if every photo of these individuals gets put into that one cluster, I'll never be able to separate them. On the other hand this scenario is becoming more and more likely as the face recognition is learning from existing clusters.


And on a side note: IMO Memories is 'carrying' recognize along with it as (from my experience) managing the clusters in the Photos app is a nightmare...so thanks for your work @pulsejet !

**Comment by pulsejet** [comment] 2023-01-19 18:30
I don't know the internals of recognize, so I don't know if this might disrupt something about the clustering process. @marcelklehr wonder if you have any thoughts? Also I believe this needs to be implemented as part of the recognize WebDAV API (I guess [here](https://github.com/nextcloud/recognize/blob/2c130d7a598dc007f0994d499bba47542d848ba3/lib/Dav/Faces/FaceRoot.php#L74)) so memories doesn't touch recognize internals.

**Comment by EVOTk** [comment] 2023-04-21 16:15
I am looking forward to it. Do you know when it will be possible? 
Thank you

**Comment by pulsejet** [comment] 2023-04-21 16:18
The relevant support in recognize is already [merged](https://github.com/nextcloud/recognize/commit/628dfa036284b653aa607b72ff91c4ca92809ecb) but we're still waiting for a new stable release there.

**Comment by EVOTk** [comment] 2023-04-21 16:20
Okay, thx for prompt reply

**Comment by luxzg** [comment] 2023-04-21 19:22
> The relevant support in recognize is already [merged](https://github.com/nextcloud/recognize/commit/628dfa036284b653aa607b72ff91c4ca92809ecb) but we're still waiting for a new stable release there.

But that was released already (?)
https://github.com/nextcloud/recognize/issues/603#issuecomment-1491958062

Or am I reading something wrong?

**Comment by EVOTk** [comment] 2023-04-21 19:29
merged after recognize v3.7.0
We have to wait for the next version of recognize  :(

**Comment by luxzg** [comment] 2023-04-21 19:36
Ah, I was mistaken, as it was same day. I'll ask there then :)

**Comment by EVOTk** [comment] 2023-04-27 21:03
Reognize [v3.8.0](https://github.com/nextcloud/recognize/releases/tag/v3.8.0) and [v4.0.1](https://github.com/nextcloud/recognize/releases/tag/v4.0.1) available :D

**Closed** 2023-04-29 07:16 UTC
Labels: feature

**Comment by luxzg** [comment] 2023-04-29 09:44
Thanks for adding this!
Due to breaking change, I assume we will be waiting for something like 6.0 release? Looking forward to it! :)

**Comment by pulsejet** [comment] 2023-04-29 11:35
It'll just be 5.1, since it's only a minor upgrade to recognize :)

**Comment by EVOTk** [comment] 2023-04-29 11:49
I can't wait 😁🤣

**Comment by luxzg** [comment] 2023-04-29 18:52
Wait is over! Thank you pulse! 🥇

**Comment by pulsejet** [comment] 2023-04-29 19:03
Now to hope it actually works 😆

**Comment by luxzg** [comment] 2023-04-29 19:37
> Now to hope it actually works 😆

Can confirm it works, tested on just one person but if it works on one it should work always :)

I've selected 14 photos, ... Menu, move to person, big "+" icon that's first in people list (new!!), added name, and confirmed I want to move to that new name. Done!

Thanks a million, now I have a lot of work to do to sort so many people ;D

**Comment by EVOTk** [comment] 2023-04-29 20:01
It works very well :) You are my hero :D

**Comment by RikkiBC** [comment] 2023-04-30 08:03
Came to find this. Saw this ticket months ago but didn't realise it was back on the cards recently. Upgraded Recognize a day or two ago, and Memories today, and it works, smooth as silk (so far haha)!

A big +1 from this Nextcloud AIO on ARM user here 🙂

**Comment by jtrees** [comment] 2023-05-01 11:23
Came here to say thank you! Works for me.
