### ISSUE TITLE
Cannot edit picture in memories app

### ISSUE THREAD

**Issue by lexiconzero** [pulsejet/memories#328] opened 2023-01-06 03:32 UTC
Nextcloud version: 25.0.2 snap Ubuntu 22.04.01
Memories version: 4.9.3
Browser: tested with latest firefox 108.0.1

Description:
When clicking the edit button on any photo via the memories app, a toast style notification will pop up with a sad robot and text displaying: "Error in loading the image with the provided url: https://nextcloud.<host>/index.php/remote.php/dav/files/<user>/<picture path>.jpg"

In the browser console as a warning, the following appears each time (with or without clicking edit):
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (1789440 px). Occurrences of will-change over the budget will be ignored.

and 

Source map error: Error: request failed with status 404
Resource URL: https://nextcloud.<host>/extra-apps/memories/js/memories-main.js?v=2c4478c8-0
Source Map URL: memories-main.js.map?v=c6b73299111908960edb

**Comment by pulsejet** [comment] 2023-01-08 04:55
Duplicate of #289

**Closed by pulsejet** 2023-01-08 04:55 UTC
