### ISSUE TITLE
Show path of file in info/metadata sidebar

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#786] opened 2023-08-23 12:39 UTC
**Is your feature request related to a problem? Please describe.**
I feel like this was possible in the past, but currently there is no way (that i can see) to see the path of the media file via the sidebar:
![image](https://github.com/pulsejet/memories/assets/10717998/f9a5ece0-3dd6-421d-905e-40c7efa2ce18)

**Describe the solution you'd like**
The metadata tab in the info sidebar should probably contain another item that lists the source file path of the photo/video

**Describe alternatives you've considered**
The only alternative seems to be to (open in folder) which brings nextcloud to a crawl when trying to list all the thousands of photos in the default nextcloud files app.

**Additional context**
For live photos we should probably just list the path to the photo (not the added video file - if it has one).

**Comment by pulsejet** [comment] 2023-08-23 14:24
Duplicate of #173
This is fairly easy actually, I'm just stuck on the UI. In many cases, this is just noise, so something like a collapsible field might be ideal.

**Closed as completed** 2023-08-23 14:34 UTC
Labels: feature
