### ISSUE TITLE
Add possibility to move Face from Cluster to NEW Person

### ISSUE THREAD

**Issue by Wastl2IT** [pulsejet/memories#509] opened 2023-03-22 06:34 UTC
Some faces may be placed in a wrong cluster. It is possible to move them to another, existing, person. But there is no possibility to create a new person.
I have clusters with some hundreds of different faces after initial recognition and it's impossible to sort them manually without the possibility to create new persons.
The option should be placed in:
Step into cluster; mark picture (with face); open the submenu (three dots ... ); right next to "move to person" add "move to new person" or something similar

**Comment by pulsejet** [comment] 2023-03-22 07:14
Duplicate of #117

**Closed by pulsejet** 2023-03-22 07:14 UTC
Labels: feature
