### ISSUE TITLE
Adopt tags fron other apps

### ISSUE THREAD

**Issue by JoeHardi** [pulsejet/memories#1323] opened 2024-10-26 13:58 UTC
### Describe the bug

When tagging pictures ans videos in other apps like "Max" or "Dad" e.g. Aves Libre those tags are not adopted. On the other hand, geodata is being adopted. Maintainer from Aves Libre said: "Aves uses standard XMP metadata format for tags. It's a problem with the other app."

### Steps To Reproduce

1. Tag a picture in Aves Libre
2. Upload it to Memories
3. Tags gone, geodata is available
4. Have to tag again

### Platform

```markdown
- OS: Android 21-20241025-microG-pdx214
- Browser: In-App
- Memories Version: 1.12
- Nextcloud Version: 3.30.2
- PHP Version: 8.1
```

**Comment by pulsejet** [comment] 2024-11-01 23:36
Duplicate of #891 #127

**Closed by pulsejet** 2024-11-01 23:36 UTC
Labels: feature
