### ISSUE TITLE
Can not add shared photo to album

### ISSUE THREAD

**Issue by MarkWieczorek** [pulsejet/memories#814] opened 2023-09-11 10:26 UTC
**Describe the bug**
I have an album that I created with photos from my nextcloud account. Another user on my instance shared a folder of photos with me and gave me all permissions to edit and delete their shared photos. I would like to add some of these shared photos to the album I created. However, when attempting to do so, I receive the error: 

```
Failed to add /photos/user1/albums/photo.jpg to album.
``` 

If this is not a bug, then this issue should be filed as a feature request. At a minimum, the error message should be more informative, like "It is not possible to add shared photos to albums".

**To Reproduce**
* Have a user share a folder of photos with you and ask them to give you privileges to edit and delete the photos.
* In your account, click on the photo, and then click to add to an album that you previously created.
* You get the above error.

**Platform:**

- OS: [e.g. iOS]: ubuntu 22.04.3
- Browser: [e.g. Chrome, Safari]: firefox
- Memories Version: [e.g. 4.1.0]: 5.4.1
- Nextcloud Version: [e.g. 25.0.6]: 27.0.2
- PHP Version: [e.g. 8.1] 8.1.2

**Additional context**

- Any errors in the JS console? The error "Failed to add /photos/user1/albums/photo.jpg to album." is shown on the screen.
- Any errors in the Nextcloud server logs? No

**Comment by pulsejet** [comment] 2023-09-12 16:03
Duplicate of #669

**Closed by pulsejet** 2023-09-12 16:03 UTC
Labels: needs triage
