### ISSUE TITLE
Memories can't access folders whose name contains special Unicode characters

### ISSUE THREAD

**Issue by ldaverio** [pulsejet/memories#658] opened 2023-05-20 12:09 UTC
Memories can't access folders whose name contains special characters, even though these folders are valid and accepted by NextCloud. My guess is that Memory sanitizes folder names too aggressively, removing perfectly valid Unicode characters.

**To Reproduce**
- from the "Files" tab, create a folder named `a–b`. Make sure to use an "EN Dash" character (`U+2013`), not a regular dash.
- Put a JPEG file in it.
- The folder, and contained image, are visible and accessible (screenshot 1).
- Switch to the "Photos" tab. The folder and image are still accessible
- Switch to the "Memories" tab. Notice how the image is absent from the timeline.
- Click on "Folders" in the next column. Notice that the folder is shown in the list, as well as the thumbnail of the photo (screenshot 2)
- Click on the folder. You get an empty page, with a popup saying "Folder not found: /{username}/files/ab" (screenshot 3)

**Screenshots:**

Screenshot 1:
<img width="717" alt="Capture d’écran 2023-05-20 à 13 57 19" src="https://github.com/pulsejet/memories/assets/8393625/77c8cb81-94db-4028-8744-6cf8e1a4238e">

Screenshot 2: 
<img width="244" alt="Capture d’écran 2023-05-20 à 13 57 38" src="https://github.com/pulsejet/memories/assets/8393625/11a541b4-037e-421c-9c46-c4475bb8ca0f">

Screenshot 3:
<img width="1221" alt="Capture d’écran 2023-05-20 à 13 58 43" src="https://github.com/pulsejet/memories/assets/8393625/1459e9de-5a7b-4311-a62d-aab42d215322">

**Platform:**

- OS: FreeBSD 13.2-RELEASE, amd64
- Browser: Firefox 113.0.1
- Memories Version: 5.1.0
- Nextcloud Version: 26.0.1
- PHP Version: 8.0.28

**Comment by pulsejet** [comment] 2023-05-20 18:26
This is already fixed on master :)

Duplicate of #635

**Closed by pulsejet** 2023-05-20 18:26 UTC
Labels: bug

**Comment by ldaverio** [comment] 2023-05-20 20:48
> Duplicate of #635

I did try to find if it was already referenced, but I only looked for "character" or "special", not "emoji". Thanks anyway :)
