### ISSUE TITLE
Problem with editing fotos from memories fotos preview

### ISSUE THREAD

**Issue by newr90** [pulsejet/memories#327] opened 2023-01-04 11:56 UTC
Hello all,
first of all I want to thank you for the great app you 've developed. It works very good and is better than the integrated photos app. Especially the livephoto function for iphone users is great.

I've only got one problem with editing any foto by clicking 
![grafik](https://user-images.githubusercontent.com/60462913/210549346-708b5312-a91b-4a60-901a-30d5b766cb67.png).
It drops an error: 
![grafik](https://user-images.githubusercontent.com/60462913/210549679-63f17dfa-83e4-4957-aa89-5bc832624992.png)
But the path seems wrong:
index.php/remote.php/dav/files/
should be just 
remote.php/dav/files/
Which seems like a bug.

Or am I missing a setting anywhere?
Thank you for your work

**Comment by pulsejet** [comment] 2023-01-04 19:16
Duplicate of #289

**Closed by pulsejet** 2023-01-04 19:16 UTC
