### ISSUE TITLE
Memories as mobile app

### ISSUE THREAD

**Issue by aposteo** [pulsejet/memories#300] opened 2022-12-18 23:38 UTC
Hi, 

it would be nice if there was a Memories-App for smartphones and tablets, where you can share and manage your images. In my opinion it´s a bit uncomfortable to do it in the web browser;)

greets alex

**Comment by HyCore** [comment] 2022-12-19 10:02
Hi, that would be awsome ! In the meantime, what you can do, is open it in chrome, firefox or edge (mobile browser) and once connected and over the memory app, you can make them as "application" by selection "add to the welcome screen" or something like that. It will be shown on your phone, now as an app, and will be much faster that previously.

**Comment by pulsejet** [comment] 2022-12-19 23:33
Duplicate of #180

**Closed by pulsejet** 2022-12-19 23:33 UTC
