### ISSUE TITLE
Share with Password

### ISSUE THREAD

**Issue by jacksbox** [pulsejet/memories#1286] opened 2024-09-09 16:01 UTC
**Is your feature request related to a problem? Please describe.**
Shared Albums / Photos etc. are publicly available for everyone with the link.

**Describe the solution you'd like**
Add the possibility to protect shares with a password.

**Comment by pulsejet** [comment] 2024-09-10 03:35
Duplicate of #348

**Closed by pulsejet** 2024-09-10 03:35 UTC
Labels: feature
