### ISSUE TITLE
Why can't we create index from UI?

### ISSUE THREAD

**Issue by mykola-dev** [pulsejet/memories#441] opened 2023-02-25 09:45 UTC
Manual says:
`Run php occ memories:index to generate metadata indices for existing photos.`
why? i mean isn't it a bad user experience when I'm being asked to execute cli commands each time I want to upload some photos? this is the only thing stopping me from using this neat app. it would be nice if this command runs automatically on each upload/delete. or at least to have some button on the ui.

**Comment by RikkiBC** [comment] 2023-02-25 11:47
Just for context: You only have to do this once, when you first install the app.

It would be a nice to have to not have to do it that one time too :) But yeah it's not something you need to do after the first time you do it so it's not that much of an issue (in my personal opinion, at least).

**Comment by pulsejet** [comment] 2023-02-25 19:18
So the reasons this has been held back:
1. It's just not high priority. As a Nextcloud admin, you'll need to use occ once in a while anyway; this is a very high-effort low-reward feature.
2. It makes debugging more difficult. If there's a button in the UI that does this in the background, if something goes wrong you'll need to find some log file to debug it. It's easier when the error is in front of you.
3. As @RikkiBC pointed out, this is a one time process. You DO NOT need to run it every time you upload some photos. As far as the first time is concerned, only the admin needs to run it, so it's not related to _user_ experience.

Closing as duplicate of #110

**Closed by pulsejet** 2023-02-25 19:18 UTC
