### ISSUE TITLE
Q: How do I select multiple photos

### ISSUE THREAD

**Issue by stomko11** [pulsejet/memories#414] opened 2023-02-12 23:15 UTC
Hello. I like latest feature of being able to select photos by selecting them from timeline. However I have an album which is contained within a folder, and I would like to move all of them to Album. I miss option "select all" or at least being able to hold down shift and select last photo to mark them all.

My side question is - I have few folders with photos, default photos app sees them correctly, but in Memories, I had to turn on "show hidden folders", I see the folders but there are no previews and/or files displayed.

**Comment by pulsejet** [comment] 2023-02-13 01:03
You can do Shift+Select, just don't select too many in one click.

> My side question is - I have few folders with photos, default photos app sees them correctly, but in Memories, I had to turn on "show hidden folders", I see the folders but there are no previews and/or files displayed.

Did you run `occ memories:index`? By any chance do these photos have a `.nomedia` file in them?

**Comment by stomko11** [comment] 2023-02-13 13:26
Thanks for response. 'occ memories:index ' did that, not sure how I missed it.
However in regards to selecting multiple files - no matter if I am in timeline, or navigate to "folders" - when I select 1st photo, and then hold down shift and select 4th photo below it, it does not do anything, just marks 4th photo in addition to 1st one, it does not select photos in between.

**Comment by pulsejet** [comment] 2023-02-13 16:28
Are you clicking on the photo (not the checkmark) when you're clicking on the 4th photo?

**Comment by stomko11** [comment] 2023-02-13 20:37
I was indeed clicking checkmark. That was the issue. Thanks.
Still, "select all" would be nice option.

**Comment by pulsejet** [comment] 2023-02-13 20:41
Duplicate of #132

**Closed by pulsejet** 2023-02-13 20:41 UTC
Labels: question
