### ISSUE TITLE
Non-admin (regular) user can't play videos

### ISSUE THREAD

**Issue by dm-vodopyanov** [pulsejet/memories#365] opened 2023-01-22 19:03 UTC
**Nextcloud:** 24.0.9
**Memories:** 3.10.1

**To reproduce:** admin user (ADMIN) has folder with videos on external storage (mentioning external storage just in case). Let it be /ADMIN/files/videos. ADMIN shares this folder to user USER, read-only access. USER creates folder "my_folder" and moves shared videos folder to "my_folder". USER tries to open some video in /USER/files/my_folder/videos through Memories but it doesn't play and error message appears: **The media could not be loaded, either because the server or network failed or because the format is not supported.**

**Investigation:** the video which USER tries to play in browser is playable in browser for ADMIN. E.g., ADMIN opens video in browser, everything is ok, then logging out, USER logs in in the same browser, tries to open the same video - can't play it and receives error message. Meanwhile, the video is playable for USER in Files. So looks like Memories-specific bug.

**Screenshot:**
![repro](https://user-images.githubusercontent.com/5374181/213934540-0640c56e-218a-45fb-9e54-9cf8e517a8c6.png)

**Comment by pulsejet** [comment] 2023-01-22 19:58
Likely duplicate of #361 
Can you try the patch in that issue?

**Comment by dm-vodopyanov** [comment] 2023-01-22 20:39
> Likely duplicate of #361 Can you try the patch in that issue?

Thank you @pulsejet, confirming that the patch works for me as well (and for https://github.com/pulsejet/memories/issues/366 too). And thank you very much for your work! For me, this is the best photo gallary app in comparison with Photoprism, Photoview, PiGallery2, Piwigo and LibrePhotos - all of them have different showstoppers on Raspberry Pi 4, which make them  unusable, and your plugin is very stable on Raspberry Pi 4, performance and usability are great, full of features, and, of course, seamless integration with Nextcloud.

**Closed** 2023-01-22 20:39 UTC
Labels: bug, duplicate

**Comment by pulsejet** [comment] 2023-01-22 23:00
Great to know that 😄
