### ISSUE TITLE
don't work with firefox under linux

### ISSUE THREAD

**Issue by enthalpie91** [pulsejet/memories#799] opened 2023-08-30 13:55 UTC
**Describe the bug**
i create a link to share photos
the link is change with firefox , when i open the link in opera it is oK
https://cloud.aas-cyclo.fr/index.php/apps/memories/s/KczynDyZXFnq877

**Screenshots**

**Platform:**
server : OS linux 5.1

- OS: [Linux on workstation opensuse leap 15.4
- Browser: firefox 115.1
- Memories Version: 5.4.1
- Nextcloud Version: 27.x

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by enthalpie91** [comment] 2023-08-30 16:31
I have try to reproduce
undr windows 10
on firefox 116.0.3 OK
on Edge 114.0  OK

**Comment by enthalpie91** [comment] 2023-08-30 20:26
sorry the link is here
https://cloud.aas-cyclo.fr/index.php/apps/memories/s/7AY7DQnGY7rYjQP

**Comment by pulsejet** [comment] 2023-08-30 20:29
Ah now I see. This isn't specific to the browser but it's happening because you're logged in with firefox.
Duplicate of #716
This is fixed with the next release.

**Closed** 2023-08-30 20:37 UTC
Labels: duplicate
