### ISSUE TITLE
trigger setup fails

### ISSUE THREAD

**Issue by Chaos99** [pulsejet/memories#1309] opened 2024-10-07 13:00 UTC
### Error message: 
```
 Repair steps for Memories
     - External table schema seem up to date
     - WARNING: Failed to create filecache trigger (compatibility mode will be used): An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "TRIGGER"
LINE 1: CREATE OR REPLACE TRIGGER memories_fcu_trg
```

### Steps To Reproduce

- Updated to Nextcloud 28.0.7
- Installed Memories from the Nextcloud App Store -> Already error message while installing on App Dashboard
- Used configuration page in admin settings -> see warning that triggers could not be activated
- Executed 'sudo -u www-data php8.3 occ maintenance:repair --include-expensive` as part of Nextcloud update finalization and received error message
- Executed `sudo -u www-data php8.3 occ maintenance:repair` as instructed in the Troubleshooting guide and received same error message again.

### Platform

```markdown
- OS: Debian Linux 5.10.0-32-amd64 x86_64
- Browser: Chrome 129.0xx
- Memories Version: 7.4.1
- Nextcloud Version: 29.0.7
- PHP Version: 8.3.11
```

**Comment by pulsejet** [comment] 2024-10-12 19:23
Duplicate of #1106

**Closed** 2024-10-12 19:23 UTC
Labels: needs triage
