### ISSUE TITLE
Error `Folder is locked` when archiving multiple photos/videos

### ISSUE THREAD

**Issue by theronakpatel** [pulsejet/memories#681] opened 2023-06-05 09:22 UTC
**Describe the bug**
When you select multiple image/video, and select `archive` , it shows `Folder is locked` error.

**To Reproduce**
1. Select multiple photos/videos
2. Goto menu , select `Archive` option
3. Displays error 

**Screenshots**

![imatge](https://github.com/pulsejet/memories/assets/11226784/3a0d2db5-7849-4d07-a355-f7c5df1c1f99)

**Platform:**

- Browser: [e.g. Chrome, Safari]
- Memories Version: [e.g. 4.1.0]
- Nextcloud Version: [e.g. 25.0.6]
- PHP Version: [e.g. 8.1]

**Additional context**

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

**Comment by pulsejet** [comment] 2023-06-05 22:11
Are you using redis?

**Comment by theronakpatel** [comment] 2023-06-06 12:46
> Are you using redis?

Yes.

**Comment by theronakpatel** [comment] 2023-07-07 17:27
Any update ?

**Comment by EpochalEngineer** [comment] 2023-07-09 15:29
Out of curiosity, what were the considerations when implementing archiving as moving to an .archive folder?

I personally wouldn't mind having an Archive tag or even user-specific Archive tag even if it shows up in other nextcloud apps, though not sure what else this would effect.

**Comment by pulsejet** [comment] 2023-07-23 21:40
> Any update ?

I haven't been able to reproduce this easily. There should be a log somewhere of which line this happens at. One possibility is the folder creation and other is the actual file movement, which would affect the correct solution.

> Out of curiosity, what were the considerations when implementing archiving as moving to an .archive folder?

The archive folder can be placed on a cold storage or moved out periodically to save space.

**Comment by eil047** [comment] 2023-10-14 11:52
The same error happens when you use Memories on 'External folders' where Nextcloud/Memories (intentionally) doesn't have the permissions to create .archive folders and moving files to that folder. So working with tags would certainly be a better - more universal - design choice

**Comment by pulsejet** [comment] 2023-10-14 18:18
> So working with tags would certainly be a better - more universal - design choice

Most certainly not. For starters, tags are stored inside the database, not the file, so this means if you want to migrate out of Memories to something else, you either need a dedicated migration script or some common export format to capture this (very crusial) information (of course the same applies to other tags, but it may be much easier to migrate these with EXIF/XMP tags, but the "archive" tag might mean something completely different at the target app).

To be clear, I'm not against having secondary functionality to hide photos from the timeline with a tag on them. Basically the issue here is performance -- checking that a file is physically outside timeline paths is much faster than filtering out using a tag. Now we already do this for the favorites view in some sense but that's a special case because you likely won't have a million photos as favorites (but your timeline most certainly will).

**Comment by eil047** [comment] 2023-10-15 10:47
I guess that the migration of the archived tag is only a (small) part of the migration of the albums information that every user will be interested in when he wants to move out/in another app.

As long as the archiving concept is not generalized between apps, working with tags seems like the softer approach which imposes/affects less other apps that work on the same data structure.

**Closed** 2023-10-30 19:30 UTC
Labels: bug
